// Database transaction constants
export const dbTransactionKeys = {
  BEGIN: 'BEGIN',
  COMMIT: 'COMMIT',
  ROLLBACK: 'ROLLBACK',
};

export const lookupTypeKeys = {
  USER_ROLE: 'USER_ROLE',
  USER_STATUS: 'USER_STATUS',
  TENANT_STATUS: 'TENANT_STATUS',
  CHAT_TYPE: 'CHAT_TYPE',
};

export const userRoleKeys = {
  USER_ROLE_PLATFORM_SUPER_ADMIN: 'USER_ROLE_PLATFORM_SUPER_ADMIN',
  USER_ROLE_PLATFORM_ADMIN: 'USER_ROLE_PLATFORM_ADMIN',
  USER_ROLE_PLATFORM_USER: 'USER_ROLE_PLATFORM_USER',
  USER_ROLE_TENANT_ADMIN: 'USER_ROLE_TENANT_ADMIN',
  USER_ROLE_TENANT_MANAGER: 'USER_ROLE_TENANT_MANAGER',
  USER_ROLE_TENANT_USER: 'USER_ROLE_TENANT_USER',
};

export const userStatusKeys = {
  USER_STATUS_PENDING: 'USER_STATUS_PENDING',
  USER_STATUS_ACTIVE: 'USER_STATUS_ACTIVE',
  USER_STATUS_DEACTIVATED: 'USER_STATUS_DEACTIVATED',
  USER_STATUS_ARCHIVED: 'USER_STATUS_ARCHIVED',
};

export const tenantStatusKeys = {
  TENANT_STATUS_PENDING: 'TENANT_STATUS_PENDING',
  TENANT_STATUS_ACTIVE: 'TENANT_STATUS_ACTIVE',
  TENANT_STATUS_DEACTIVATED: 'TENANT_STATUS_DEACTIVATED',
  TENANT_STATUS_ARCHIVED: 'TENANT_STATUS_ARCHIVED',
};

export const chatTypeKeys = {
  CHAT_TYPE_ONE_TO_ONE: 'CHAT_TYPE_ONE_TO_ONE',
  CHAT_TYPE_GROUP: 'CHAT_TYPE_GROUP',
};
